jobs:
  test:
    working_directory: /go/src/github.com/gjbae1212/hit-counter
    docker:
      - image: circleci/golang:1.17
    environment:
      GOPATH: /go
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.2
          docker_layer_caching: false
      - run:
          name: Install Git lfs
          command: |
            sudo apt-get install git-lfs
            git lfs install
      - run:
          name: Pull Git lfs
          command: git lfs pull
      - run:
          name: Unit Test
          environment:
          command: bash script/build.sh test

workflows:
  version: 2
  build-deploy:
    jobs:
      - test:
          filters:
            branches:
              only:
                - /feature.*/
                - develop
                - master
                - production
